"""empty message

Revision ID: 3452ed51b565
Revises: 6b0bd5701650
Create Date: 2018-03-25 19:31:32.139917

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3452ed51b565'
down_revision = '6b0bd5701650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion',
                    sa.Column('discussionid', sa.Integer(), nullable=False),
                    sa.Column('discussiontitle', sa.String(length=50), nullable=False),
                    sa.Column('discussiondateposted', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('discussionid')
                    )
    op.create_table('discussion_user',
                    sa.Column('discussion_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['discussion_id'], ['discussion.discussionid'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=40), nullable=False),
                    sa.Column('body', sa.String(length=255), nullable=False),
                    sa.Column('read', sa.Boolean(), nullable=False),
                    sa.Column('ref', sa.String(length=255), nullable=False),
                    sa.Column('recipient', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['recipient'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('subscription',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('post', sa.Integer(), nullable=False),
                    sa.Column('subscriber', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
                    sa.ForeignKeyConstraint(['subscriber'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription')
    op.drop_table('notification')
    op.drop_table('discussion_user')
    op.drop_table('discussion')
    # ### end Alembic commands ###
