"""empty message

Revision ID: 96c767a93183
Revises: f932fc64c3fb
Create Date: 2018-03-21 20:01:25.447940

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '96c767a93183'
down_revision = 'f932fc64c3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_group',
                    sa.Column('discussionid', sa.Integer(), nullable=False),
                    sa.Column('discussiontitle', sa.String(length=50), nullable=False),
                    sa.Column('discussionbody', sa.String(length=255), nullable=False),
                    sa.Column('discussiondateposted', sa.String(length=100), nullable=False),
                    sa.Column('discussionposter_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['discussionposter_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('discussionid')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discussion_group')
    # ### end Alembic commands ###
