"""empty message

Revision ID: e50c4a15d7ca
Revises: ca049c721f72
Create Date: 2018-04-05 12:19:17.767129

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e50c4a15d7ca'
down_revision = 'ca049c721f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'discussion', ['group_id'], ['discussionid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'group_id')
    # ### end Alembic commands ###
