"""empty message

Revision ID: f932fc64c3fb
Revises: c224ceb38450
Create Date: 2018-03-18 16:04:55.831266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f932fc64c3fb'
down_revision = 'c224ceb38450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=50), nullable=False),
                    sa.Column('body', sa.String(length=255), nullable=False),
                    sa.Column('poster_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['poster_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
